INSERT INTO posts (title, message, creator, tags, Image, likeCount)
VALUES
    ('Exploring Nature', 'Spent the day hiking and exploring the beautiful forest trails.', 'Adventurer123', 'nature, hiking, outdoors', 'https://png.pngtree.com/thumb_back/fh260/background/20210902/pngtree-summer-mountain-sunrise-and-sunset-scenery-clouds-natural-scenery-natural-scenery-image_789792.jpg', 25),
    ('Delicious Homemade Recipe', 'Tried a new recipe today and it turned out amazing!', 'FoodieChef', 'cooking, recipes, food', 'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2018/12/Shakshuka-19.jpg', 38),
    ('Artistic Creations', 'Finished this painting I have been working on for weeks.', 'ArtEnthusiast', 'art, painting, creativity', 'https://cdn.cdnparenting.com/articles/2018/06/731247928-H.jpg', 15),
    ('Travel Memories', 'Throwback to the incredible views and experiences during my last trip.', 'WanderlustTraveler', 'travel, adventure, memories', 'https://media.istockphoto.com/id/1285301614/photo/young-man-arms-outstretched-by-the-sea-at-sunrise-enjoying-freedom-and-life-people-travel.jpg?s=612x612&w=0&k=20&c=0QW6GnkuFNYcPZhy26XVHuTc2avJTK8u6l_1iT0SlZk=', 42),
    ('Fitness Journey', 'Completed a challenging workout today and feeling great!', 'FitnessFanatic', 'fitness, health, exercise', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Zml0bmVzc3xlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80', 12),
    ('Sunday Relaxation', 'Enjoying a calm and peaceful Sunday afternoon with a good book.', 'Bookworm123', 'books, reading, relaxation', 'https://img.etimg.com/thumb/width-1200,height-900,imgsize-24942,resizemode-75,msid-98117524/top-trending-products/books/10-best-novels-for-beginners-to-read-this-year.jpg', 8),
    ('Music Jam Session', 'Had a fun jamming session with friends, creating some great music.', 'MusicMaker', 'music, jamming, creativity', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80', 20),
    ('Tech Gadgets', 'Unboxed the latest tech gadget - excited to try out its features!', 'TechGeek', 'technology, gadgets, innovation', 'https://pikwizard.com/pw/small/b3b05919d3d51215bba77b22f6949309.jpg', 32),
    ('Community Cleanup', 'Participated in a local community cleanup event to make our neighborhood cleaner.', 'CommunityActivist', 'community, environment, volunteering', 'https://img.freepik.com/free-photo/successful-happy-business-team_53876-25180.jpg', 5),
    ('Family Time', 'Spent quality time with family at the park, creating beautiful memories.', 'FamilyFirst', 'family, bonding, love', 'https://img.freepik.com/free-photo/medium-shot-happy-family-nature_23-2148996570.jpg', 18);
